name: Gerar EXE
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install pymupdf lxml customtkinter tkinterdnd2 pyinstaller
      - run: python -m PyInstaller --onefile --windowed --name SuprimirImagens --collect-all customtkinter --collect-all tkinterdnd2 --clean suprimir_imagens.py
      - uses: actions/upload-artifact@v4
        with:
          name: SuprimirImagens-Windows
          path: dist/SuprimirImagens.exe

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install pymupdf lxml customtkinter tkinterdnd2 pyinstaller
      - run: python -m PyInstaller --onedir --windowed --name SuprimirImagens --collect-all customtkinter --collect-all tkinterdnd2 --clean suprimir_imagens.py
      - run: ditto -c -k --keepParent dist/SuprimirImagens.app dist/SuprimirImagens-Mac.zip
      - uses: actions/upload-artifact@v4
        with:
          name: SuprimirImagens-Mac
          path: dist/SuprimirImagens-Mac.zip
